INSERT INTO form(description) VALUES('Math questioning');
INSERT INTO form(description) VALUES('Math questioning');
INSERT INTO form(description) VALUES('Math questioning');
INSERT INTO form(description) VALUES('Math questioning');
INSERT INTO form(description) VALUES('Math questioning');
INSERT INTO form(description) VALUES('Math questioning');
INSERT INTO form(description) VALUES('Math questioning');
INSERT INTO form(description) VALUES('Math questioning');
INSERT INTO form(description) VALUES('Math questioning');
INSERT INTO form(description) VALUES('Math questioning');
INSERT INTO question(form_id, description) VALUES(1, '180 + -922 = ');
INSERT INTO question(form_id, description) VALUES(1, '499 + -986 = ');
INSERT INTO question(form_id, description) VALUES(1, '837 + 278 = ');
INSERT INTO question(form_id, description) VALUES(1, '794 + -511 = ');
INSERT INTO question(form_id, description) VALUES(1, '390 + -515 = ');
INSERT INTO question(form_id, description) VALUES(1, '-802 + 338 = ');
INSERT INTO question(form_id, description) VALUES(1, '477 + -887 = ');
INSERT INTO question(form_id, description) VALUES(1, '-588 + 993 = ');
INSERT INTO question(form_id, description) VALUES(1, '-420 + -572 = ');
INSERT INTO question(form_id, description) VALUES(1, '-669 + -152 = ');
INSERT INTO question(form_id, description) VALUES(1, '463 + -717 = ');
INSERT INTO question(form_id, description) VALUES(1, '-858 + -816 = ');
INSERT INTO question(form_id, description) VALUES(1, '-63 + -837 = ');
INSERT INTO question(form_id, description) VALUES(1, '-348 + 813 = ');
INSERT INTO question(form_id, description) VALUES(1, '758 + 389 = ');
INSERT INTO question(form_id, description) VALUES(1, '-497 + -84 = ');
INSERT INTO question(form_id, description) VALUES(1, '-774 + 997 = ');
INSERT INTO question(form_id, description) VALUES(1, '-321 + -29 = ');
INSERT INTO question(form_id, description) VALUES(1, '-116 + 380 = ');
INSERT INTO question(form_id, description) VALUES(1, '357 + 397 = ');
INSERT INTO question(form_id, description) VALUES(2, '-668 + 538 = ');
INSERT INTO question(form_id, description) VALUES(2, '884 + -299 = ');
INSERT INTO question(form_id, description) VALUES(2, '192 + 844 = ');
INSERT INTO question(form_id, description) VALUES(2, '554 + -405 = ');
INSERT INTO question(form_id, description) VALUES(2, '-602 + -998 = ');
INSERT INTO question(form_id, description) VALUES(2, '-900 + 371 = ');
INSERT INTO question(form_id, description) VALUES(2, '43 + -106 = ');
INSERT INTO question(form_id, description) VALUES(2, '249 + -766 = ');
INSERT INTO question(form_id, description) VALUES(2, '-507 + -928 = ');
INSERT INTO question(form_id, description) VALUES(2, '501 + -99 = ');
INSERT INTO question(form_id, description) VALUES(2, '774 + -127 = ');
INSERT INTO question(form_id, description) VALUES(2, '-670 + 495 = ');
INSERT INTO question(form_id, description) VALUES(2, '-386 + -827 = ');
INSERT INTO question(form_id, description) VALUES(2, '753 + 230 = ');
INSERT INTO question(form_id, description) VALUES(2, '347 + -306 = ');
INSERT INTO question(form_id, description) VALUES(2, '72 + 227 = ');
INSERT INTO question(form_id, description) VALUES(2, '170 + -774 = ');
INSERT INTO question(form_id, description) VALUES(2, '-144 + 842 = ');
INSERT INTO question(form_id, description) VALUES(2, '-78 + 28 = ');
INSERT INTO question(form_id, description) VALUES(2, '61 + 417 = ');
INSERT INTO question(form_id, description) VALUES(3, '-205 + -373 = ');
INSERT INTO question(form_id, description) VALUES(3, '309 + 598 = ');
INSERT INTO question(form_id, description) VALUES(3, '73 + -674 = ');
INSERT INTO question(form_id, description) VALUES(3, '72 + 518 = ');
INSERT INTO question(form_id, description) VALUES(3, '-185 + -280 = ');
INSERT INTO question(form_id, description) VALUES(3, '-580 + -363 = ');
INSERT INTO question(form_id, description) VALUES(3, '713 + -101 = ');
INSERT INTO question(form_id, description) VALUES(3, '-243 + -321 = ');
INSERT INTO question(form_id, description) VALUES(3, '253 + 3 = ');
INSERT INTO question(form_id, description) VALUES(3, '-552 + -797 = ');
INSERT INTO question(form_id, description) VALUES(3, '236 + 714 = ');
INSERT INTO question(form_id, description) VALUES(3, '-776 + 23 = ');
INSERT INTO question(form_id, description) VALUES(3, '-925 + -128 = ');
INSERT INTO question(form_id, description) VALUES(3, '-133 + 353 = ');
INSERT INTO question(form_id, description) VALUES(3, '489 + 455 = ');
INSERT INTO question(form_id, description) VALUES(3, '-820 + 651 = ');
INSERT INTO question(form_id, description) VALUES(3, '-645 + -277 = ');
INSERT INTO question(form_id, description) VALUES(3, '-845 + 774 = ');
INSERT INTO question(form_id, description) VALUES(3, '-552 + 677 = ');
INSERT INTO question(form_id, description) VALUES(3, '728 + 49 = ');
INSERT INTO question(form_id, description) VALUES(4, '705 + 636 = ');
INSERT INTO question(form_id, description) VALUES(4, '398 + -665 = ');
INSERT INTO question(form_id, description) VALUES(4, '-104 + 7 = ');
INSERT INTO question(form_id, description) VALUES(4, '-689 + -158 = ');
INSERT INTO question(form_id, description) VALUES(4, '-858 + -793 = ');
INSERT INTO question(form_id, description) VALUES(4, '709 + 100 = ');
INSERT INTO question(form_id, description) VALUES(4, '-800 + 697 = ');
INSERT INTO question(form_id, description) VALUES(4, '526 + -929 = ');
INSERT INTO question(form_id, description) VALUES(4, '826 + -446 = ');
INSERT INTO question(form_id, description) VALUES(4, '18 + 887 = ');
INSERT INTO question(form_id, description) VALUES(4, '692 + -30 = ');
INSERT INTO question(form_id, description) VALUES(4, '-102 + 272 = ');
INSERT INTO question(form_id, description) VALUES(4, '-240 + 471 = ');
INSERT INTO question(form_id, description) VALUES(4, '777 + 806 = ');
INSERT INTO question(form_id, description) VALUES(4, '-84 + 667 = ');
INSERT INTO question(form_id, description) VALUES(4, '-169 + 911 = ');
INSERT INTO question(form_id, description) VALUES(4, '-68 + 586 = ');
INSERT INTO question(form_id, description) VALUES(4, '-584 + 942 = ');
INSERT INTO question(form_id, description) VALUES(4, '-770 + -397 = ');
INSERT INTO question(form_id, description) VALUES(4, '86 + 863 = ');
INSERT INTO question(form_id, description) VALUES(5, '224 + 632 = ');
INSERT INTO question(form_id, description) VALUES(5, '495 + -157 = ');
INSERT INTO question(form_id, description) VALUES(5, '219 + 692 = ');
INSERT INTO question(form_id, description) VALUES(5, '328 + -542 = ');
INSERT INTO question(form_id, description) VALUES(5, '-952 + 78 = ');
INSERT INTO question(form_id, description) VALUES(5, '-208 + 859 = ');
INSERT INTO question(form_id, description) VALUES(5, '924 + -518 = ');
INSERT INTO question(form_id, description) VALUES(5, '-134 + -443 = ');
INSERT INTO question(form_id, description) VALUES(5, '467 + 518 = ');
INSERT INTO question(form_id, description) VALUES(5, '-47 + -920 = ');
INSERT INTO question(form_id, description) VALUES(5, '538 + -315 = ');
INSERT INTO question(form_id, description) VALUES(5, '-123 + 620 = ');
INSERT INTO question(form_id, description) VALUES(5, '532 + -465 = ');
INSERT INTO question(form_id, description) VALUES(5, '185 + 476 = ');
INSERT INTO question(form_id, description) VALUES(5, '-744 + -172 = ');
INSERT INTO question(form_id, description) VALUES(5, '742 + -940 = ');
INSERT INTO question(form_id, description) VALUES(5, '595 + -340 = ');
INSERT INTO question(form_id, description) VALUES(5, '57 + 998 = ');
INSERT INTO question(form_id, description) VALUES(5, '-217 + -635 = ');
INSERT INTO question(form_id, description) VALUES(5, '919 + 697 = ');
INSERT INTO question(form_id, description) VALUES(6, '341 + -412 = ');
INSERT INTO question(form_id, description) VALUES(6, '379 + -521 = ');
INSERT INTO question(form_id, description) VALUES(6, '863 + 458 = ');
INSERT INTO question(form_id, description) VALUES(6, '137 + 488 = ');
INSERT INTO question(form_id, description) VALUES(6, '-595 + 940 = ');
INSERT INTO question(form_id, description) VALUES(6, '749 + -624 = ');
INSERT INTO question(form_id, description) VALUES(6, '46 + 945 = ');
INSERT INTO question(form_id, description) VALUES(6, '776 + -763 = ');
INSERT INTO question(form_id, description) VALUES(6, '354 + -784 = ');
INSERT INTO question(form_id, description) VALUES(6, '-209 + 886 = ');
INSERT INTO question(form_id, description) VALUES(6, '-594 + 395 = ');
INSERT INTO question(form_id, description) VALUES(6, '-609 + 682 = ');
INSERT INTO question(form_id, description) VALUES(6, '-598 + 106 = ');
INSERT INTO question(form_id, description) VALUES(6, '691 + -684 = ');
INSERT INTO question(form_id, description) VALUES(6, '-331 + 95 = ');
INSERT INTO question(form_id, description) VALUES(6, '261 + -932 = ');
INSERT INTO question(form_id, description) VALUES(6, '-401 + -291 = ');
INSERT INTO question(form_id, description) VALUES(6, '689 + 1 = ');
INSERT INTO question(form_id, description) VALUES(6, '389 + -419 = ');
INSERT INTO question(form_id, description) VALUES(6, '873 + 629 = ');
INSERT INTO question(form_id, description) VALUES(7, '-601 + 103 = ');
INSERT INTO question(form_id, description) VALUES(7, '696 + -159 = ');
INSERT INTO question(form_id, description) VALUES(7, '642 + 105 = ');
INSERT INTO question(form_id, description) VALUES(7, '-520 + 913 = ');
INSERT INTO question(form_id, description) VALUES(7, '-545 + -980 = ');
INSERT INTO question(form_id, description) VALUES(7, '605 + -845 = ');
INSERT INTO question(form_id, description) VALUES(7, '-196 + 609 = ');
INSERT INTO question(form_id, description) VALUES(7, '-206 + -447 = ');
INSERT INTO question(form_id, description) VALUES(7, '413 + 452 = ');
INSERT INTO question(form_id, description) VALUES(7, '-991 + -855 = ');
INSERT INTO question(form_id, description) VALUES(7, '-618 + -129 = ');
INSERT INTO question(form_id, description) VALUES(7, '-134 + 241 = ');
INSERT INTO question(form_id, description) VALUES(7, '962 + -531 = ');
INSERT INTO question(form_id, description) VALUES(7, '-448 + 28 = ');
INSERT INTO question(form_id, description) VALUES(7, '-413 + 66 = ');
INSERT INTO question(form_id, description) VALUES(7, '-632 + -21 = ');
INSERT INTO question(form_id, description) VALUES(7, '62 + -956 = ');
INSERT INTO question(form_id, description) VALUES(7, '-886 + -587 = ');
INSERT INTO question(form_id, description) VALUES(7, '-639 + 513 = ');
INSERT INTO question(form_id, description) VALUES(7, '-40 + 109 = ');
INSERT INTO question(form_id, description) VALUES(8, '-504 + 873 = ');
INSERT INTO question(form_id, description) VALUES(8, '378 + 328 = ');
INSERT INTO question(form_id, description) VALUES(8, '106 + -608 = ');
INSERT INTO question(form_id, description) VALUES(8, '705 + -754 = ');
INSERT INTO question(form_id, description) VALUES(8, '718 + 477 = ');
INSERT INTO question(form_id, description) VALUES(8, '-135 + 57 = ');
INSERT INTO question(form_id, description) VALUES(8, '-173 + -242 = ');
INSERT INTO question(form_id, description) VALUES(8, '-66 + 188 = ');
INSERT INTO question(form_id, description) VALUES(8, '576 + 443 = ');
INSERT INTO question(form_id, description) VALUES(8, '-516 + 437 = ');
INSERT INTO question(form_id, description) VALUES(8, '326 + -766 = ');
INSERT INTO question(form_id, description) VALUES(8, '276 + -721 = ');
INSERT INTO question(form_id, description) VALUES(8, '560 + 839 = ');
INSERT INTO question(form_id, description) VALUES(8, '-183 + 210 = ');
INSERT INTO question(form_id, description) VALUES(8, '620 + -766 = ');
INSERT INTO question(form_id, description) VALUES(8, '-979 + 913 = ');
INSERT INTO question(form_id, description) VALUES(8, '-486 + -580 = ');
INSERT INTO question(form_id, description) VALUES(8, '-232 + -243 = ');
INSERT INTO question(form_id, description) VALUES(8, '329 + 904 = ');
INSERT INTO question(form_id, description) VALUES(8, '-984 + -21 = ');
INSERT INTO question(form_id, description) VALUES(9, '-122 + -928 = ');
INSERT INTO question(form_id, description) VALUES(9, '-910 + -446 = ');
INSERT INTO question(form_id, description) VALUES(9, '-774 + -760 = ');
INSERT INTO question(form_id, description) VALUES(9, '670 + -64 = ');
INSERT INTO question(form_id, description) VALUES(9, '-845 + -843 = ');
INSERT INTO question(form_id, description) VALUES(9, '-549 + -663 = ');
INSERT INTO question(form_id, description) VALUES(9, '728 + 452 = ');
INSERT INTO question(form_id, description) VALUES(9, '-170 + 104 = ');
INSERT INTO question(form_id, description) VALUES(9, '705 + 328 = ');
INSERT INTO question(form_id, description) VALUES(9, '-487 + -635 = ');
INSERT INTO question(form_id, description) VALUES(9, '-846 + -649 = ');
INSERT INTO question(form_id, description) VALUES(9, '-685 + 535 = ');
INSERT INTO question(form_id, description) VALUES(9, '1 + 657 = ');
INSERT INTO question(form_id, description) VALUES(9, '707 + 578 = ');
INSERT INTO question(form_id, description) VALUES(9, '-417 + -624 = ');
INSERT INTO question(form_id, description) VALUES(9, '166 + -323 = ');
INSERT INTO question(form_id, description) VALUES(9, '-211 + -544 = ');
INSERT INTO question(form_id, description) VALUES(9, '495 + -940 = ');
INSERT INTO question(form_id, description) VALUES(9, '214 + 887 = ');
INSERT INTO question(form_id, description) VALUES(9, '99 + 207 = ');
INSERT INTO question(form_id, description) VALUES(10, '353 + 431 = ');
INSERT INTO question(form_id, description) VALUES(10, '399 + -420 = ');
INSERT INTO question(form_id, description) VALUES(10, '695 + -322 = ');
INSERT INTO question(form_id, description) VALUES(10, '-857 + 170 = ');
INSERT INTO question(form_id, description) VALUES(10, '-478 + 216 = ');
INSERT INTO question(form_id, description) VALUES(10, '984 + 889 = ');
INSERT INTO question(form_id, description) VALUES(10, '496 + -188 = ');
INSERT INTO question(form_id, description) VALUES(10, '-135 + 412 = ');
INSERT INTO question(form_id, description) VALUES(10, '-943 + -734 = ');
INSERT INTO question(form_id, description) VALUES(10, '-804 + -757 = ');
INSERT INTO question(form_id, description) VALUES(10, '395 + -177 = ');
INSERT INTO question(form_id, description) VALUES(10, '-135 + 752 = ');
INSERT INTO question(form_id, description) VALUES(10, '257 + 437 = ');
INSERT INTO question(form_id, description) VALUES(10, '-990 + -449 = ');
INSERT INTO question(form_id, description) VALUES(10, '970 + 94 = ');
INSERT INTO question(form_id, description) VALUES(10, '932 + -287 = ');
INSERT INTO question(form_id, description) VALUES(10, '-27 + 999 = ');
INSERT INTO question(form_id, description) VALUES(10, '68 + 262 = ');
INSERT INTO question(form_id, description) VALUES(10, '493 + 788 = ');
INSERT INTO question(form_id, description) VALUES(10, '-133 + -337 = ');
INSERT INTO choice(question_id, description) VALUES(1, '-705');
INSERT INTO choice(question_id, description) VALUES(1, '-484');
INSERT INTO choice(question_id, description) VALUES(1, '-584');
INSERT INTO choice(question_id, description) VALUES(1, '728');
INSERT INTO choice(question_id, description) VALUES(1, '-742');
INSERT INTO choice(question_id, description) VALUES(2, '-777');
INSERT INTO choice(question_id, description) VALUES(2, '-255');
INSERT INTO choice(question_id, description) VALUES(2, '782');
INSERT INTO choice(question_id, description) VALUES(2, '-782');
INSERT INTO choice(question_id, description) VALUES(2, '-487');
INSERT INTO choice(question_id, description) VALUES(3, '635');
INSERT INTO choice(question_id, description) VALUES(3, '-837');
INSERT INTO choice(question_id, description) VALUES(3, '-991');
INSERT INTO choice(question_id, description) VALUES(3, '-142');
INSERT INTO choice(question_id, description) VALUES(3, '1115');
INSERT INTO choice(question_id, description) VALUES(4, '-272');
INSERT INTO choice(question_id, description) VALUES(4, '-406');
INSERT INTO choice(question_id, description) VALUES(4, '739');
INSERT INTO choice(question_id, description) VALUES(4, '-404');
INSERT INTO choice(question_id, description) VALUES(4, '283');
INSERT INTO choice(question_id, description) VALUES(5, '-513');
INSERT INTO choice(question_id, description) VALUES(5, '-758');
INSERT INTO choice(question_id, description) VALUES(5, '-192');
INSERT INTO choice(question_id, description) VALUES(5, '6');
INSERT INTO choice(question_id, description) VALUES(5, '-125');
INSERT INTO choice(question_id, description) VALUES(6, '360');
INSERT INTO choice(question_id, description) VALUES(6, '848');
INSERT INTO choice(question_id, description) VALUES(6, '627');
INSERT INTO choice(question_id, description) VALUES(6, '-997');
INSERT INTO choice(question_id, description) VALUES(6, '-464');
INSERT INTO choice(question_id, description) VALUES(7, '790');
INSERT INTO choice(question_id, description) VALUES(7, '191');
INSERT INTO choice(question_id, description) VALUES(7, '553');
INSERT INTO choice(question_id, description) VALUES(7, '132');
INSERT INTO choice(question_id, description) VALUES(7, '-410');
INSERT INTO choice(question_id, description) VALUES(8, '906');
INSERT INTO choice(question_id, description) VALUES(8, '-35');
INSERT INTO choice(question_id, description) VALUES(8, '-34');
INSERT INTO choice(question_id, description) VALUES(8, '-370');
INSERT INTO choice(question_id, description) VALUES(8, '405');
INSERT INTO choice(question_id, description) VALUES(9, '-220');
INSERT INTO choice(question_id, description) VALUES(9, '145');
INSERT INTO choice(question_id, description) VALUES(9, '-830');
INSERT INTO choice(question_id, description) VALUES(9, '263');
INSERT INTO choice(question_id, description) VALUES(9, '-992');
INSERT INTO choice(question_id, description) VALUES(10, '83');
INSERT INTO choice(question_id, description) VALUES(10, '394');
INSERT INTO choice(question_id, description) VALUES(10, '820');
INSERT INTO choice(question_id, description) VALUES(10, '693');
INSERT INTO choice(question_id, description) VALUES(10, '-821');
INSERT INTO choice(question_id, description) VALUES(11, '406');
INSERT INTO choice(question_id, description) VALUES(11, '960');
INSERT INTO choice(question_id, description) VALUES(11, '281');
INSERT INTO choice(question_id, description) VALUES(11, '559');
INSERT INTO choice(question_id, description) VALUES(11, '-254');
INSERT INTO choice(question_id, description) VALUES(12, '-755');
INSERT INTO choice(question_id, description) VALUES(12, '418');
INSERT INTO choice(question_id, description) VALUES(12, '-762');
INSERT INTO choice(question_id, description) VALUES(12, '-786');
INSERT INTO choice(question_id, description) VALUES(12, '-1674');
INSERT INTO choice(question_id, description) VALUES(13, '-997');
INSERT INTO choice(question_id, description) VALUES(13, '277');
INSERT INTO choice(question_id, description) VALUES(13, '609');
INSERT INTO choice(question_id, description) VALUES(13, '-982');
INSERT INTO choice(question_id, description) VALUES(13, '-900');
INSERT INTO choice(question_id, description) VALUES(14, '521');
INSERT INTO choice(question_id, description) VALUES(14, '-463');
INSERT INTO choice(question_id, description) VALUES(14, '-552');
INSERT INTO choice(question_id, description) VALUES(14, '-292');
INSERT INTO choice(question_id, description) VALUES(14, '465');
INSERT INTO choice(question_id, description) VALUES(15, '-501');
INSERT INTO choice(question_id, description) VALUES(15, '145');
INSERT INTO choice(question_id, description) VALUES(15, '-670');
INSERT INTO choice(question_id, description) VALUES(15, '872');
INSERT INTO choice(question_id, description) VALUES(15, '1147');
INSERT INTO choice(question_id, description) VALUES(16, '-695');
INSERT INTO choice(question_id, description) VALUES(16, '-750');
INSERT INTO choice(question_id, description) VALUES(16, '-959');
INSERT INTO choice(question_id, description) VALUES(16, '927');
INSERT INTO choice(question_id, description) VALUES(16, '-581');
INSERT INTO choice(question_id, description) VALUES(17, '-795');
INSERT INTO choice(question_id, description) VALUES(17, '847');
INSERT INTO choice(question_id, description) VALUES(17, '586');
INSERT INTO choice(question_id, description) VALUES(17, '-315');
INSERT INTO choice(question_id, description) VALUES(17, '223');
INSERT INTO choice(question_id, description) VALUES(18, '982');
INSERT INTO choice(question_id, description) VALUES(18, '260');
INSERT INTO choice(question_id, description) VALUES(18, '-543');
INSERT INTO choice(question_id, description) VALUES(18, '5');
INSERT INTO choice(question_id, description) VALUES(18, '-350');
INSERT INTO choice(question_id, description) VALUES(19, '-982');
INSERT INTO choice(question_id, description) VALUES(19, '-834');
INSERT INTO choice(question_id, description) VALUES(19, '-364');
INSERT INTO choice(question_id, description) VALUES(19, '-925');
INSERT INTO choice(question_id, description) VALUES(19, '264');
INSERT INTO choice(question_id, description) VALUES(20, '157');
INSERT INTO choice(question_id, description) VALUES(20, '-100');
INSERT INTO choice(question_id, description) VALUES(20, '176');
INSERT INTO choice(question_id, description) VALUES(20, '-527');
INSERT INTO choice(question_id, description) VALUES(20, '754');
INSERT INTO choice(question_id, description) VALUES(21, '361');
INSERT INTO choice(question_id, description) VALUES(21, '587');
INSERT INTO choice(question_id, description) VALUES(21, '957');
INSERT INTO choice(question_id, description) VALUES(21, '658');
INSERT INTO choice(question_id, description) VALUES(21, '-130');
INSERT INTO choice(question_id, description) VALUES(22, '-140');
INSERT INTO choice(question_id, description) VALUES(22, '-756');
INSERT INTO choice(question_id, description) VALUES(22, '-249');
INSERT INTO choice(question_id, description) VALUES(22, '-148');
INSERT INTO choice(question_id, description) VALUES(22, '585');
INSERT INTO choice(question_id, description) VALUES(23, '715');
INSERT INTO choice(question_id, description) VALUES(23, '-906');
INSERT INTO choice(question_id, description) VALUES(23, '662');
INSERT INTO choice(question_id, description) VALUES(23, '-970');
INSERT INTO choice(question_id, description) VALUES(23, '1036');
INSERT INTO choice(question_id, description) VALUES(24, '-260');
INSERT INTO choice(question_id, description) VALUES(24, '-14');
INSERT INTO choice(question_id, description) VALUES(24, '-699');
INSERT INTO choice(question_id, description) VALUES(24, '-632');
INSERT INTO choice(question_id, description) VALUES(24, '149');
INSERT INTO choice(question_id, description) VALUES(25, '954');
INSERT INTO choice(question_id, description) VALUES(25, '636');
INSERT INTO choice(question_id, description) VALUES(25, '548');
INSERT INTO choice(question_id, description) VALUES(25, '-70');
INSERT INTO choice(question_id, description) VALUES(25, '-1600');
INSERT INTO choice(question_id, description) VALUES(26, '96');
INSERT INTO choice(question_id, description) VALUES(26, '-568');
INSERT INTO choice(question_id, description) VALUES(26, '431');
INSERT INTO choice(question_id, description) VALUES(26, '-774');
INSERT INTO choice(question_id, description) VALUES(26, '-529');
INSERT INTO choice(question_id, description) VALUES(27, '194');
INSERT INTO choice(question_id, description) VALUES(27, '-990');
INSERT INTO choice(question_id, description) VALUES(27, '243');
INSERT INTO choice(question_id, description) VALUES(27, '-807');
INSERT INTO choice(question_id, description) VALUES(27, '-63');
INSERT INTO choice(question_id, description) VALUES(28, '-470');
INSERT INTO choice(question_id, description) VALUES(28, '905');
INSERT INTO choice(question_id, description) VALUES(28, '266');
INSERT INTO choice(question_id, description) VALUES(28, '-866');
INSERT INTO choice(question_id, description) VALUES(28, '-517');
INSERT INTO choice(question_id, description) VALUES(29, '365');
INSERT INTO choice(question_id, description) VALUES(29, '-818');
INSERT INTO choice(question_id, description) VALUES(29, '461');
INSERT INTO choice(question_id, description) VALUES(29, '763');
INSERT INTO choice(question_id, description) VALUES(29, '-1435');
INSERT INTO choice(question_id, description) VALUES(30, '-971');
INSERT INTO choice(question_id, description) VALUES(30, '-398');
INSERT INTO choice(question_id, description) VALUES(30, '689');
INSERT INTO choice(question_id, description) VALUES(30, '370');
INSERT INTO choice(question_id, description) VALUES(30, '402');
INSERT INTO choice(question_id, description) VALUES(31, '798');
INSERT INTO choice(question_id, description) VALUES(31, '-906');
INSERT INTO choice(question_id, description) VALUES(31, '244');
INSERT INTO choice(question_id, description) VALUES(31, '72');
INSERT INTO choice(question_id, description) VALUES(31, '647');
INSERT INTO choice(question_id, description) VALUES(32, '435');
INSERT INTO choice(question_id, description) VALUES(32, '339');
INSERT INTO choice(question_id, description) VALUES(32, '668');
INSERT INTO choice(question_id, description) VALUES(32, '758');
INSERT INTO choice(question_id, description) VALUES(32, '-175');
INSERT INTO choice(question_id, description) VALUES(33, '-117');
INSERT INTO choice(question_id, description) VALUES(33, '610');
INSERT INTO choice(question_id, description) VALUES(33, '-719');
INSERT INTO choice(question_id, description) VALUES(33, '-380');
INSERT INTO choice(question_id, description) VALUES(33, '-1213');
INSERT INTO choice(question_id, description) VALUES(34, '-3');
INSERT INTO choice(question_id, description) VALUES(34, '878');
INSERT INTO choice(question_id, description) VALUES(34, '918');
INSERT INTO choice(question_id, description) VALUES(34, '812');
INSERT INTO choice(question_id, description) VALUES(34, '983');
INSERT INTO choice(question_id, description) VALUES(35, '645');
INSERT INTO choice(question_id, description) VALUES(35, '-280');
INSERT INTO choice(question_id, description) VALUES(35, '-354');
INSERT INTO choice(question_id, description) VALUES(35, '-81');
INSERT INTO choice(question_id, description) VALUES(35, '41');
INSERT INTO choice(question_id, description) VALUES(36, '-958');
INSERT INTO choice(question_id, description) VALUES(36, '963');
INSERT INTO choice(question_id, description) VALUES(36, '-365');
INSERT INTO choice(question_id, description) VALUES(36, '249');
INSERT INTO choice(question_id, description) VALUES(36, '299');
INSERT INTO choice(question_id, description) VALUES(37, '-879');
INSERT INTO choice(question_id, description) VALUES(37, '360');
INSERT INTO choice(question_id, description) VALUES(37, '806');
INSERT INTO choice(question_id, description) VALUES(37, '-632');
INSERT INTO choice(question_id, description) VALUES(37, '-604');
INSERT INTO choice(question_id, description) VALUES(38, '-416');
INSERT INTO choice(question_id, description) VALUES(38, '805');
INSERT INTO choice(question_id, description) VALUES(38, '494');
INSERT INTO choice(question_id, description) VALUES(38, '64');
INSERT INTO choice(question_id, description) VALUES(38, '698');
INSERT INTO choice(question_id, description) VALUES(39, '540');
INSERT INTO choice(question_id, description) VALUES(39, '746');
INSERT INTO choice(question_id, description) VALUES(39, '437');
INSERT INTO choice(question_id, description) VALUES(39, '789');
INSERT INTO choice(question_id, description) VALUES(39, '-50');
INSERT INTO choice(question_id, description) VALUES(40, '342');
INSERT INTO choice(question_id, description) VALUES(40, '-505');
INSERT INTO choice(question_id, description) VALUES(40, '-239');
INSERT INTO choice(question_id, description) VALUES(40, '295');
INSERT INTO choice(question_id, description) VALUES(40, '478');
INSERT INTO choice(question_id, description) VALUES(41, '909');
INSERT INTO choice(question_id, description) VALUES(41, '-29');
INSERT INTO choice(question_id, description) VALUES(41, '976');
INSERT INTO choice(question_id, description) VALUES(41, '448');
INSERT INTO choice(question_id, description) VALUES(41, '-578');
INSERT INTO choice(question_id, description) VALUES(42, '906');
INSERT INTO choice(question_id, description) VALUES(42, '-845');
INSERT INTO choice(question_id, description) VALUES(42, '-654');
INSERT INTO choice(question_id, description) VALUES(42, '-30');
INSERT INTO choice(question_id, description) VALUES(42, '907');
INSERT INTO choice(question_id, description) VALUES(43, '369');
INSERT INTO choice(question_id, description) VALUES(43, '272');
INSERT INTO choice(question_id, description) VALUES(43, '444');
INSERT INTO choice(question_id, description) VALUES(43, '193');
INSERT INTO choice(question_id, description) VALUES(43, '-601');
INSERT INTO choice(question_id, description) VALUES(44, '-487');
INSERT INTO choice(question_id, description) VALUES(44, '327');
INSERT INTO choice(question_id, description) VALUES(44, '-21');
INSERT INTO choice(question_id, description) VALUES(44, '-831');
INSERT INTO choice(question_id, description) VALUES(44, '590');
INSERT INTO choice(question_id, description) VALUES(45, '-461');
INSERT INTO choice(question_id, description) VALUES(45, '-13');
INSERT INTO choice(question_id, description) VALUES(45, '79');
INSERT INTO choice(question_id, description) VALUES(45, '720');
INSERT INTO choice(question_id, description) VALUES(45, '-465');
INSERT INTO choice(question_id, description) VALUES(46, '-664');
INSERT INTO choice(question_id, description) VALUES(46, '-462');
INSERT INTO choice(question_id, description) VALUES(46, '-426');
INSERT INTO choice(question_id, description) VALUES(46, '395');
INSERT INTO choice(question_id, description) VALUES(46, '-943');
INSERT INTO choice(question_id, description) VALUES(47, '952');
INSERT INTO choice(question_id, description) VALUES(47, '154');
INSERT INTO choice(question_id, description) VALUES(47, '-173');
INSERT INTO choice(question_id, description) VALUES(47, '-418');
INSERT INTO choice(question_id, description) VALUES(47, '612');
INSERT INTO choice(question_id, description) VALUES(48, '-618');
INSERT INTO choice(question_id, description) VALUES(48, '-556');
INSERT INTO choice(question_id, description) VALUES(48, '139');
INSERT INTO choice(question_id, description) VALUES(48, '-462');
INSERT INTO choice(question_id, description) VALUES(48, '-564');
INSERT INTO choice(question_id, description) VALUES(49, '170');
INSERT INTO choice(question_id, description) VALUES(49, '357');
INSERT INTO choice(question_id, description) VALUES(49, '992');
INSERT INTO choice(question_id, description) VALUES(49, '951');
INSERT INTO choice(question_id, description) VALUES(49, '256');
INSERT INTO choice(question_id, description) VALUES(50, '276');
INSERT INTO choice(question_id, description) VALUES(50, '-406');
INSERT INTO choice(question_id, description) VALUES(50, '-108');
INSERT INTO choice(question_id, description) VALUES(50, '531');
INSERT INTO choice(question_id, description) VALUES(50, '-1349');
INSERT INTO choice(question_id, description) VALUES(51, '820');
INSERT INTO choice(question_id, description) VALUES(51, '-95');
INSERT INTO choice(question_id, description) VALUES(51, '-306');
INSERT INTO choice(question_id, description) VALUES(51, '86');
INSERT INTO choice(question_id, description) VALUES(51, '950');
INSERT INTO choice(question_id, description) VALUES(52, '154');
INSERT INTO choice(question_id, description) VALUES(52, '593');
INSERT INTO choice(question_id, description) VALUES(52, '-51');
INSERT INTO choice(question_id, description) VALUES(52, '378');
INSERT INTO choice(question_id, description) VALUES(52, '-753');
INSERT INTO choice(question_id, description) VALUES(53, '148');
INSERT INTO choice(question_id, description) VALUES(53, '-125');
INSERT INTO choice(question_id, description) VALUES(53, '-158');
INSERT INTO choice(question_id, description) VALUES(53, '587');
INSERT INTO choice(question_id, description) VALUES(53, '-1053');
INSERT INTO choice(question_id, description) VALUES(54, '496');
INSERT INTO choice(question_id, description) VALUES(54, '-446');
INSERT INTO choice(question_id, description) VALUES(54, '-995');
INSERT INTO choice(question_id, description) VALUES(54, '-228');
INSERT INTO choice(question_id, description) VALUES(54, '220');
INSERT INTO choice(question_id, description) VALUES(55, '-350');
INSERT INTO choice(question_id, description) VALUES(55, '202');
INSERT INTO choice(question_id, description) VALUES(55, '884');
INSERT INTO choice(question_id, description) VALUES(55, '-882');
INSERT INTO choice(question_id, description) VALUES(55, '944');
INSERT INTO choice(question_id, description) VALUES(56, '-72');
INSERT INTO choice(question_id, description) VALUES(56, '-42');
INSERT INTO choice(question_id, description) VALUES(56, '-326');
INSERT INTO choice(question_id, description) VALUES(56, '72');
INSERT INTO choice(question_id, description) VALUES(56, '-169');
INSERT INTO choice(question_id, description) VALUES(57, '858');
INSERT INTO choice(question_id, description) VALUES(57, '265');
INSERT INTO choice(question_id, description) VALUES(57, '65');
INSERT INTO choice(question_id, description) VALUES(57, '574');
INSERT INTO choice(question_id, description) VALUES(57, '-922');
INSERT INTO choice(question_id, description) VALUES(58, '420');
INSERT INTO choice(question_id, description) VALUES(58, '934');
INSERT INTO choice(question_id, description) VALUES(58, '-164');
INSERT INTO choice(question_id, description) VALUES(58, '-456');
INSERT INTO choice(question_id, description) VALUES(58, '-71');
INSERT INTO choice(question_id, description) VALUES(59, '-870');
INSERT INTO choice(question_id, description) VALUES(59, '-635');
INSERT INTO choice(question_id, description) VALUES(59, '-84');
INSERT INTO choice(question_id, description) VALUES(59, '-457');
INSERT INTO choice(question_id, description) VALUES(59, '125');
INSERT INTO choice(question_id, description) VALUES(60, '-276');
INSERT INTO choice(question_id, description) VALUES(60, '365');
INSERT INTO choice(question_id, description) VALUES(60, '-46');
INSERT INTO choice(question_id, description) VALUES(60, '-978');
INSERT INTO choice(question_id, description) VALUES(60, '777');
INSERT INTO choice(question_id, description) VALUES(61, '-334');
INSERT INTO choice(question_id, description) VALUES(61, '998');
INSERT INTO choice(question_id, description) VALUES(61, '995');
INSERT INTO choice(question_id, description) VALUES(61, '589');
INSERT INTO choice(question_id, description) VALUES(61, '1341');
INSERT INTO choice(question_id, description) VALUES(62, '197');
INSERT INTO choice(question_id, description) VALUES(62, '-296');
INSERT INTO choice(question_id, description) VALUES(62, '869');
INSERT INTO choice(question_id, description) VALUES(62, '-450');
INSERT INTO choice(question_id, description) VALUES(62, '-267');
INSERT INTO choice(question_id, description) VALUES(63, '-963');
INSERT INTO choice(question_id, description) VALUES(63, '-863');
INSERT INTO choice(question_id, description) VALUES(63, '-684');
INSERT INTO choice(question_id, description) VALUES(63, '-631');
INSERT INTO choice(question_id, description) VALUES(63, '-97');
INSERT INTO choice(question_id, description) VALUES(64, '999');
INSERT INTO choice(question_id, description) VALUES(64, '809');
INSERT INTO choice(question_id, description) VALUES(64, '695');
INSERT INTO choice(question_id, description) VALUES(64, '693');
INSERT INTO choice(question_id, description) VALUES(64, '-847');
INSERT INTO choice(question_id, description) VALUES(65, '652');
INSERT INTO choice(question_id, description) VALUES(65, '-678');
INSERT INTO choice(question_id, description) VALUES(65, '574');
INSERT INTO choice(question_id, description) VALUES(65, '-860');
INSERT INTO choice(question_id, description) VALUES(65, '-1651');
INSERT INTO choice(question_id, description) VALUES(66, '-263');
INSERT INTO choice(question_id, description) VALUES(66, '-333');
INSERT INTO choice(question_id, description) VALUES(66, '513');
INSERT INTO choice(question_id, description) VALUES(66, '-470');
INSERT INTO choice(question_id, description) VALUES(66, '809');
INSERT INTO choice(question_id, description) VALUES(67, '166');
INSERT INTO choice(question_id, description) VALUES(67, '-433');
INSERT INTO choice(question_id, description) VALUES(67, '963');
INSERT INTO choice(question_id, description) VALUES(67, '556');
INSERT INTO choice(question_id, description) VALUES(67, '-103');
INSERT INTO choice(question_id, description) VALUES(68, '-710');
INSERT INTO choice(question_id, description) VALUES(68, '95');
INSERT INTO choice(question_id, description) VALUES(68, '363');
INSERT INTO choice(question_id, description) VALUES(68, '120');
INSERT INTO choice(question_id, description) VALUES(68, '-403');
INSERT INTO choice(question_id, description) VALUES(69, '624');
INSERT INTO choice(question_id, description) VALUES(69, '354');
INSERT INTO choice(question_id, description) VALUES(69, '-782');
INSERT INTO choice(question_id, description) VALUES(69, '205');
INSERT INTO choice(question_id, description) VALUES(69, '380');
INSERT INTO choice(question_id, description) VALUES(70, '-621');
INSERT INTO choice(question_id, description) VALUES(70, '512');
INSERT INTO choice(question_id, description) VALUES(70, '165');
INSERT INTO choice(question_id, description) VALUES(70, '420');
INSERT INTO choice(question_id, description) VALUES(70, '905');
INSERT INTO choice(question_id, description) VALUES(71, '892');
INSERT INTO choice(question_id, description) VALUES(71, '-582');
INSERT INTO choice(question_id, description) VALUES(71, '-885');
INSERT INTO choice(question_id, description) VALUES(71, '363');
INSERT INTO choice(question_id, description) VALUES(71, '662');
INSERT INTO choice(question_id, description) VALUES(72, '729');
INSERT INTO choice(question_id, description) VALUES(72, '465');
INSERT INTO choice(question_id, description) VALUES(72, '-460');
INSERT INTO choice(question_id, description) VALUES(72, '843');
INSERT INTO choice(question_id, description) VALUES(72, '170');
INSERT INTO choice(question_id, description) VALUES(73, '-19');
INSERT INTO choice(question_id, description) VALUES(73, '974');
INSERT INTO choice(question_id, description) VALUES(73, '-573');
INSERT INTO choice(question_id, description) VALUES(73, '-874');
INSERT INTO choice(question_id, description) VALUES(73, '231');
INSERT INTO choice(question_id, description) VALUES(74, '-302');
INSERT INTO choice(question_id, description) VALUES(74, '208');
INSERT INTO choice(question_id, description) VALUES(74, '-841');
INSERT INTO choice(question_id, description) VALUES(74, '-163');
INSERT INTO choice(question_id, description) VALUES(74, '1583');
INSERT INTO choice(question_id, description) VALUES(75, '-949');
INSERT INTO choice(question_id, description) VALUES(75, '-60');
INSERT INTO choice(question_id, description) VALUES(75, '711');
INSERT INTO choice(question_id, description) VALUES(75, '294');
INSERT INTO choice(question_id, description) VALUES(75, '583');
INSERT INTO choice(question_id, description) VALUES(76, '980');
INSERT INTO choice(question_id, description) VALUES(76, '893');
INSERT INTO choice(question_id, description) VALUES(76, '-943');
INSERT INTO choice(question_id, description) VALUES(76, '443');
INSERT INTO choice(question_id, description) VALUES(76, '742');
INSERT INTO choice(question_id, description) VALUES(77, '159');
INSERT INTO choice(question_id, description) VALUES(77, '-823');
INSERT INTO choice(question_id, description) VALUES(77, '-534');
INSERT INTO choice(question_id, description) VALUES(77, '-482');
INSERT INTO choice(question_id, description) VALUES(77, '518');
INSERT INTO choice(question_id, description) VALUES(78, '-192');
INSERT INTO choice(question_id, description) VALUES(78, '-370');
INSERT INTO choice(question_id, description) VALUES(78, '141');
INSERT INTO choice(question_id, description) VALUES(78, '-568');
INSERT INTO choice(question_id, description) VALUES(78, '358');
INSERT INTO choice(question_id, description) VALUES(79, '275');
INSERT INTO choice(question_id, description) VALUES(79, '-560');
INSERT INTO choice(question_id, description) VALUES(79, '-479');
INSERT INTO choice(question_id, description) VALUES(79, '-495');
INSERT INTO choice(question_id, description) VALUES(79, '-1167');
INSERT INTO choice(question_id, description) VALUES(80, '266');
INSERT INTO choice(question_id, description) VALUES(80, '-970');
INSERT INTO choice(question_id, description) VALUES(80, '-227');
INSERT INTO choice(question_id, description) VALUES(80, '474');
INSERT INTO choice(question_id, description) VALUES(80, '949');
INSERT INTO choice(question_id, description) VALUES(81, '-699');
INSERT INTO choice(question_id, description) VALUES(81, '-348');
INSERT INTO choice(question_id, description) VALUES(81, '74');
INSERT INTO choice(question_id, description) VALUES(81, '-786');
INSERT INTO choice(question_id, description) VALUES(81, '856');
INSERT INTO choice(question_id, description) VALUES(82, '-910');
INSERT INTO choice(question_id, description) VALUES(82, '-691');
INSERT INTO choice(question_id, description) VALUES(82, '-16');
INSERT INTO choice(question_id, description) VALUES(82, '-230');
INSERT INTO choice(question_id, description) VALUES(82, '338');
INSERT INTO choice(question_id, description) VALUES(83, '806');
INSERT INTO choice(question_id, description) VALUES(83, '-808');
INSERT INTO choice(question_id, description) VALUES(83, '504');
INSERT INTO choice(question_id, description) VALUES(83, '-876');
INSERT INTO choice(question_id, description) VALUES(83, '911');
INSERT INTO choice(question_id, description) VALUES(84, '-541');
INSERT INTO choice(question_id, description) VALUES(84, '-145');
INSERT INTO choice(question_id, description) VALUES(84, '-134');
INSERT INTO choice(question_id, description) VALUES(84, '27');
INSERT INTO choice(question_id, description) VALUES(84, '-214');
INSERT INTO choice(question_id, description) VALUES(85, '601');
INSERT INTO choice(question_id, description) VALUES(85, '-926');
INSERT INTO choice(question_id, description) VALUES(85, '352');
INSERT INTO choice(question_id, description) VALUES(85, '435');
INSERT INTO choice(question_id, description) VALUES(85, '-874');
INSERT INTO choice(question_id, description) VALUES(86, '-240');
INSERT INTO choice(question_id, description) VALUES(86, '-546');
INSERT INTO choice(question_id, description) VALUES(86, '-742');
INSERT INTO choice(question_id, description) VALUES(86, '553');
INSERT INTO choice(question_id, description) VALUES(86, '651');
INSERT INTO choice(question_id, description) VALUES(87, '801');
INSERT INTO choice(question_id, description) VALUES(87, '-864');
INSERT INTO choice(question_id, description) VALUES(87, '-495');
INSERT INTO choice(question_id, description) VALUES(87, '-674');
INSERT INTO choice(question_id, description) VALUES(87, '406');
INSERT INTO choice(question_id, description) VALUES(88, '825');
INSERT INTO choice(question_id, description) VALUES(88, '-128');
INSERT INTO choice(question_id, description) VALUES(88, '752');
INSERT INTO choice(question_id, description) VALUES(88, '-861');
INSERT INTO choice(question_id, description) VALUES(88, '-577');
INSERT INTO choice(question_id, description) VALUES(89, '-557');
INSERT INTO choice(question_id, description) VALUES(89, '-622');
INSERT INTO choice(question_id, description) VALUES(89, '-277');
INSERT INTO choice(question_id, description) VALUES(89, '128');
INSERT INTO choice(question_id, description) VALUES(89, '985');
INSERT INTO choice(question_id, description) VALUES(90, '-582');
INSERT INTO choice(question_id, description) VALUES(90, '-772');
INSERT INTO choice(question_id, description) VALUES(90, '513');
INSERT INTO choice(question_id, description) VALUES(90, '-933');
INSERT INTO choice(question_id, description) VALUES(90, '-967');
INSERT INTO choice(question_id, description) VALUES(91, '730');
INSERT INTO choice(question_id, description) VALUES(91, '-17');
INSERT INTO choice(question_id, description) VALUES(91, '901');
INSERT INTO choice(question_id, description) VALUES(91, '-560');
INSERT INTO choice(question_id, description) VALUES(91, '223');
INSERT INTO choice(question_id, description) VALUES(92, '-500');
INSERT INTO choice(question_id, description) VALUES(92, '-993');
INSERT INTO choice(question_id, description) VALUES(92, '535');
INSERT INTO choice(question_id, description) VALUES(92, '180');
INSERT INTO choice(question_id, description) VALUES(92, '497');
INSERT INTO choice(question_id, description) VALUES(93, '-504');
INSERT INTO choice(question_id, description) VALUES(93, '857');
INSERT INTO choice(question_id, description) VALUES(93, '355');
INSERT INTO choice(question_id, description) VALUES(93, '843');
INSERT INTO choice(question_id, description) VALUES(93, '67');
INSERT INTO choice(question_id, description) VALUES(94, '310');
INSERT INTO choice(question_id, description) VALUES(94, '390');
INSERT INTO choice(question_id, description) VALUES(94, '-417');
INSERT INTO choice(question_id, description) VALUES(94, '-281');
INSERT INTO choice(question_id, description) VALUES(94, '661');
INSERT INTO choice(question_id, description) VALUES(95, '-422');
INSERT INTO choice(question_id, description) VALUES(95, '-905');
INSERT INTO choice(question_id, description) VALUES(95, '691');
INSERT INTO choice(question_id, description) VALUES(95, '-189');
INSERT INTO choice(question_id, description) VALUES(95, '-916');
INSERT INTO choice(question_id, description) VALUES(96, '-400');
INSERT INTO choice(question_id, description) VALUES(96, '665');
INSERT INTO choice(question_id, description) VALUES(96, '53');
INSERT INTO choice(question_id, description) VALUES(96, '577');
INSERT INTO choice(question_id, description) VALUES(96, '-198');
INSERT INTO choice(question_id, description) VALUES(97, '377');
INSERT INTO choice(question_id, description) VALUES(97, '-263');
INSERT INTO choice(question_id, description) VALUES(97, '518');
INSERT INTO choice(question_id, description) VALUES(97, '-318');
INSERT INTO choice(question_id, description) VALUES(97, '255');
INSERT INTO choice(question_id, description) VALUES(98, '-204');
INSERT INTO choice(question_id, description) VALUES(98, '258');
INSERT INTO choice(question_id, description) VALUES(98, '346');
INSERT INTO choice(question_id, description) VALUES(98, '-809');
INSERT INTO choice(question_id, description) VALUES(98, '1055');
INSERT INTO choice(question_id, description) VALUES(99, '467');
INSERT INTO choice(question_id, description) VALUES(99, '-153');
INSERT INTO choice(question_id, description) VALUES(99, '-566');
INSERT INTO choice(question_id, description) VALUES(99, '547');
INSERT INTO choice(question_id, description) VALUES(99, '-852');
INSERT INTO choice(question_id, description) VALUES(100, '920');
INSERT INTO choice(question_id, description) VALUES(100, '-958');
INSERT INTO choice(question_id, description) VALUES(100, '-695');
INSERT INTO choice(question_id, description) VALUES(100, '-860');
INSERT INTO choice(question_id, description) VALUES(100, '1616');
INSERT INTO choice(question_id, description) VALUES(101, '722');
INSERT INTO choice(question_id, description) VALUES(101, '519');
INSERT INTO choice(question_id, description) VALUES(101, '-45');
INSERT INTO choice(question_id, description) VALUES(101, '-68');
INSERT INTO choice(question_id, description) VALUES(101, '-71');
INSERT INTO choice(question_id, description) VALUES(102, '207');
INSERT INTO choice(question_id, description) VALUES(102, '-250');
INSERT INTO choice(question_id, description) VALUES(102, '-566');
INSERT INTO choice(question_id, description) VALUES(102, '-645');
INSERT INTO choice(question_id, description) VALUES(102, '-142');
INSERT INTO choice(question_id, description) VALUES(103, '887');
INSERT INTO choice(question_id, description) VALUES(103, '387');
INSERT INTO choice(question_id, description) VALUES(103, '810');
INSERT INTO choice(question_id, description) VALUES(103, '467');
INSERT INTO choice(question_id, description) VALUES(103, '1321');
INSERT INTO choice(question_id, description) VALUES(104, '527');
INSERT INTO choice(question_id, description) VALUES(104, '-789');
INSERT INTO choice(question_id, description) VALUES(104, '-917');
INSERT INTO choice(question_id, description) VALUES(104, '-693');
INSERT INTO choice(question_id, description) VALUES(104, '625');
INSERT INTO choice(question_id, description) VALUES(105, '846');
INSERT INTO choice(question_id, description) VALUES(105, '502');
INSERT INTO choice(question_id, description) VALUES(105, '496');
INSERT INTO choice(question_id, description) VALUES(105, '541');
INSERT INTO choice(question_id, description) VALUES(105, '345');
INSERT INTO choice(question_id, description) VALUES(106, '-669');
INSERT INTO choice(question_id, description) VALUES(106, '-697');
INSERT INTO choice(question_id, description) VALUES(106, '-815');
INSERT INTO choice(question_id, description) VALUES(106, '701');
INSERT INTO choice(question_id, description) VALUES(106, '125');
INSERT INTO choice(question_id, description) VALUES(107, '474');
INSERT INTO choice(question_id, description) VALUES(107, '-143');
INSERT INTO choice(question_id, description) VALUES(107, '291');
INSERT INTO choice(question_id, description) VALUES(107, '-286');
INSERT INTO choice(question_id, description) VALUES(107, '991');
INSERT INTO choice(question_id, description) VALUES(108, '-84');
INSERT INTO choice(question_id, description) VALUES(108, '-549');
INSERT INTO choice(question_id, description) VALUES(108, '-13');
INSERT INTO choice(question_id, description) VALUES(108, '702');
INSERT INTO choice(question_id, description) VALUES(108, '13');
INSERT INTO choice(question_id, description) VALUES(109, '508');
INSERT INTO choice(question_id, description) VALUES(109, '0');
INSERT INTO choice(question_id, description) VALUES(109, '717');
INSERT INTO choice(question_id, description) VALUES(109, '244');
INSERT INTO choice(question_id, description) VALUES(109, '-430');
INSERT INTO choice(question_id, description) VALUES(110, '-28');
INSERT INTO choice(question_id, description) VALUES(110, '579');
INSERT INTO choice(question_id, description) VALUES(110, '914');
INSERT INTO choice(question_id, description) VALUES(110, '-829');
INSERT INTO choice(question_id, description) VALUES(110, '677');
INSERT INTO choice(question_id, description) VALUES(111, '20');
INSERT INTO choice(question_id, description) VALUES(111, '433');
INSERT INTO choice(question_id, description) VALUES(111, '-271');
INSERT INTO choice(question_id, description) VALUES(111, '-749');
INSERT INTO choice(question_id, description) VALUES(111, '-199');
INSERT INTO choice(question_id, description) VALUES(112, '149');
INSERT INTO choice(question_id, description) VALUES(112, '532');
INSERT INTO choice(question_id, description) VALUES(112, '284');
INSERT INTO choice(question_id, description) VALUES(112, '991');
INSERT INTO choice(question_id, description) VALUES(112, '73');
INSERT INTO choice(question_id, description) VALUES(113, '-675');
INSERT INTO choice(question_id, description) VALUES(113, '568');
INSERT INTO choice(question_id, description) VALUES(113, '955');
INSERT INTO choice(question_id, description) VALUES(113, '-516');
INSERT INTO choice(question_id, description) VALUES(113, '-492');
INSERT INTO choice(question_id, description) VALUES(114, '-715');
INSERT INTO choice(question_id, description) VALUES(114, '578');
INSERT INTO choice(question_id, description) VALUES(114, '-470');
INSERT INTO choice(question_id, description) VALUES(114, '756');
INSERT INTO choice(question_id, description) VALUES(114, '7');
INSERT INTO choice(question_id, description) VALUES(115, '467');
INSERT INTO choice(question_id, description) VALUES(115, '587');
INSERT INTO choice(question_id, description) VALUES(115, '157');
INSERT INTO choice(question_id, description) VALUES(115, '513');
INSERT INTO choice(question_id, description) VALUES(115, '-236');
INSERT INTO choice(question_id, description) VALUES(116, '344');
INSERT INTO choice(question_id, description) VALUES(116, '690');
INSERT INTO choice(question_id, description) VALUES(116, '-381');
INSERT INTO choice(question_id, description) VALUES(116, '-992');
INSERT INTO choice(question_id, description) VALUES(116, '-671');
INSERT INTO choice(question_id, description) VALUES(117, '551');
INSERT INTO choice(question_id, description) VALUES(117, '-92');
INSERT INTO choice(question_id, description) VALUES(117, '697');
INSERT INTO choice(question_id, description) VALUES(117, '-748');
INSERT INTO choice(question_id, description) VALUES(117, '-692');
INSERT INTO choice(question_id, description) VALUES(118, '-566');
INSERT INTO choice(question_id, description) VALUES(118, '577');
INSERT INTO choice(question_id, description) VALUES(118, '81');
INSERT INTO choice(question_id, description) VALUES(118, '-308');
INSERT INTO choice(question_id, description) VALUES(118, '690');
INSERT INTO choice(question_id, description) VALUES(119, '-902');
INSERT INTO choice(question_id, description) VALUES(119, '-91');
INSERT INTO choice(question_id, description) VALUES(119, '-861');
INSERT INTO choice(question_id, description) VALUES(119, '-701');
INSERT INTO choice(question_id, description) VALUES(119, '-30');
INSERT INTO choice(question_id, description) VALUES(120, '247');
INSERT INTO choice(question_id, description) VALUES(120, '-984');
INSERT INTO choice(question_id, description) VALUES(120, '-504');
INSERT INTO choice(question_id, description) VALUES(120, '729');
INSERT INTO choice(question_id, description) VALUES(120, '1502');
INSERT INTO choice(question_id, description) VALUES(121, '-331');
INSERT INTO choice(question_id, description) VALUES(121, '-825');
INSERT INTO choice(question_id, description) VALUES(121, '597');
INSERT INTO choice(question_id, description) VALUES(121, '-375');
INSERT INTO choice(question_id, description) VALUES(121, '-498');
INSERT INTO choice(question_id, description) VALUES(122, '701');
INSERT INTO choice(question_id, description) VALUES(122, '493');
INSERT INTO choice(question_id, description) VALUES(122, '-562');
INSERT INTO choice(question_id, description) VALUES(122, '-999');
INSERT INTO choice(question_id, description) VALUES(122, '537');
INSERT INTO choice(question_id, description) VALUES(123, '-712');
INSERT INTO choice(question_id, description) VALUES(123, '462');
INSERT INTO choice(question_id, description) VALUES(123, '-384');
INSERT INTO choice(question_id, description) VALUES(123, '205');
INSERT INTO choice(question_id, description) VALUES(123, '747');
INSERT INTO choice(question_id, description) VALUES(124, '89');
INSERT INTO choice(question_id, description) VALUES(124, '33');
INSERT INTO choice(question_id, description) VALUES(124, '-915');
INSERT INTO choice(question_id, description) VALUES(124, '-727');
INSERT INTO choice(question_id, description) VALUES(124, '393');
INSERT INTO choice(question_id, description) VALUES(125, '-265');
INSERT INTO choice(question_id, description) VALUES(125, '-715');
INSERT INTO choice(question_id, description) VALUES(125, '-590');
INSERT INTO choice(question_id, description) VALUES(125, '-161');
INSERT INTO choice(question_id, description) VALUES(125, '-1525');
INSERT INTO choice(question_id, description) VALUES(126, '-402');
INSERT INTO choice(question_id, description) VALUES(126, '852');
INSERT INTO choice(question_id, description) VALUES(126, '-510');
INSERT INTO choice(question_id, description) VALUES(126, '-318');
INSERT INTO choice(question_id, description) VALUES(126, '-240');
INSERT INTO choice(question_id, description) VALUES(127, '-591');
INSERT INTO choice(question_id, description) VALUES(127, '-53');
INSERT INTO choice(question_id, description) VALUES(127, '-870');
INSERT INTO choice(question_id, description) VALUES(127, '124');
INSERT INTO choice(question_id, description) VALUES(127, '413');
INSERT INTO choice(question_id, description) VALUES(128, '283');
INSERT INTO choice(question_id, description) VALUES(128, '703');
INSERT INTO choice(question_id, description) VALUES(128, '-336');
INSERT INTO choice(question_id, description) VALUES(128, '811');
INSERT INTO choice(question_id, description) VALUES(128, '-653');
INSERT INTO choice(question_id, description) VALUES(129, '615');
INSERT INTO choice(question_id, description) VALUES(129, '-553');
INSERT INTO choice(question_id, description) VALUES(129, '-798');
INSERT INTO choice(question_id, description) VALUES(129, '910');
INSERT INTO choice(question_id, description) VALUES(129, '865');
INSERT INTO choice(question_id, description) VALUES(130, '745');
INSERT INTO choice(question_id, description) VALUES(130, '-505');
INSERT INTO choice(question_id, description) VALUES(130, '-307');
INSERT INTO choice(question_id, description) VALUES(130, '-711');
INSERT INTO choice(question_id, description) VALUES(130, '-1846');
INSERT INTO choice(question_id, description) VALUES(131, '843');
INSERT INTO choice(question_id, description) VALUES(131, '-550');
INSERT INTO choice(question_id, description) VALUES(131, '-586');
INSERT INTO choice(question_id, description) VALUES(131, '-113');
INSERT INTO choice(question_id, description) VALUES(131, '-747');
INSERT INTO choice(question_id, description) VALUES(132, '-72');
INSERT INTO choice(question_id, description) VALUES(132, '924');
INSERT INTO choice(question_id, description) VALUES(132, '-196');
INSERT INTO choice(question_id, description) VALUES(132, '981');
INSERT INTO choice(question_id, description) VALUES(132, '107');
INSERT INTO choice(question_id, description) VALUES(133, '-103');
INSERT INTO choice(question_id, description) VALUES(133, '-551');
INSERT INTO choice(question_id, description) VALUES(133, '-168');
INSERT INTO choice(question_id, description) VALUES(133, '837');
INSERT INTO choice(question_id, description) VALUES(133, '431');
INSERT INTO choice(question_id, description) VALUES(134, '-873');
INSERT INTO choice(question_id, description) VALUES(134, '167');
INSERT INTO choice(question_id, description) VALUES(134, '441');
INSERT INTO choice(question_id, description) VALUES(134, '666');
INSERT INTO choice(question_id, description) VALUES(134, '-420');
INSERT INTO choice(question_id, description) VALUES(135, '53');
INSERT INTO choice(question_id, description) VALUES(135, '-316');
INSERT INTO choice(question_id, description) VALUES(135, '-265');
INSERT INTO choice(question_id, description) VALUES(135, '578');
INSERT INTO choice(question_id, description) VALUES(135, '-347');
INSERT INTO choice(question_id, description) VALUES(136, '26');
INSERT INTO choice(question_id, description) VALUES(136, '80');
INSERT INTO choice(question_id, description) VALUES(136, '-106');
INSERT INTO choice(question_id, description) VALUES(136, '-469');
INSERT INTO choice(question_id, description) VALUES(136, '-653');
INSERT INTO choice(question_id, description) VALUES(137, '-451');
INSERT INTO choice(question_id, description) VALUES(137, '50');
INSERT INTO choice(question_id, description) VALUES(137, '246');
INSERT INTO choice(question_id, description) VALUES(137, '-214');
INSERT INTO choice(question_id, description) VALUES(137, '-894');
INSERT INTO choice(question_id, description) VALUES(138, '657');
INSERT INTO choice(question_id, description) VALUES(138, '-663');
INSERT INTO choice(question_id, description) VALUES(138, '610');
INSERT INTO choice(question_id, description) VALUES(138, '-927');
INSERT INTO choice(question_id, description) VALUES(138, '-1473');
INSERT INTO choice(question_id, description) VALUES(139, '-359');
INSERT INTO choice(question_id, description) VALUES(139, '446');
INSERT INTO choice(question_id, description) VALUES(139, '991');
INSERT INTO choice(question_id, description) VALUES(139, '-432');
INSERT INTO choice(question_id, description) VALUES(139, '-126');
INSERT INTO choice(question_id, description) VALUES(140, '-903');
INSERT INTO choice(question_id, description) VALUES(140, '65');
INSERT INTO choice(question_id, description) VALUES(140, '-303');
INSERT INTO choice(question_id, description) VALUES(140, '637');
INSERT INTO choice(question_id, description) VALUES(140, '69');
INSERT INTO choice(question_id, description) VALUES(141, '-632');
INSERT INTO choice(question_id, description) VALUES(141, '347');
INSERT INTO choice(question_id, description) VALUES(141, '-365');
INSERT INTO choice(question_id, description) VALUES(141, '982');
INSERT INTO choice(question_id, description) VALUES(141, '369');
INSERT INTO choice(question_id, description) VALUES(142, '-768');
INSERT INTO choice(question_id, description) VALUES(142, '179');
INSERT INTO choice(question_id, description) VALUES(142, '-425');
INSERT INTO choice(question_id, description) VALUES(142, '-16');
INSERT INTO choice(question_id, description) VALUES(142, '706');
INSERT INTO choice(question_id, description) VALUES(143, '643');
INSERT INTO choice(question_id, description) VALUES(143, '-698');
INSERT INTO choice(question_id, description) VALUES(143, '955');
INSERT INTO choice(question_id, description) VALUES(143, '-368');
INSERT INTO choice(question_id, description) VALUES(143, '-502');
INSERT INTO choice(question_id, description) VALUES(144, '16');
INSERT INTO choice(question_id, description) VALUES(144, '-833');
INSERT INTO choice(question_id, description) VALUES(144, '570');
INSERT INTO choice(question_id, description) VALUES(144, '247');
INSERT INTO choice(question_id, description) VALUES(144, '-49');
INSERT INTO choice(question_id, description) VALUES(145, '-585');
INSERT INTO choice(question_id, description) VALUES(145, '-485');
INSERT INTO choice(question_id, description) VALUES(145, '14');
INSERT INTO choice(question_id, description) VALUES(145, '-686');
INSERT INTO choice(question_id, description) VALUES(145, '1195');
INSERT INTO choice(question_id, description) VALUES(146, '182');
INSERT INTO choice(question_id, description) VALUES(146, '485');
INSERT INTO choice(question_id, description) VALUES(146, '-55');
INSERT INTO choice(question_id, description) VALUES(146, '-180');
INSERT INTO choice(question_id, description) VALUES(146, '-78');
INSERT INTO choice(question_id, description) VALUES(147, '931');
INSERT INTO choice(question_id, description) VALUES(147, '946');
INSERT INTO choice(question_id, description) VALUES(147, '-809');
INSERT INTO choice(question_id, description) VALUES(147, '-426');
INSERT INTO choice(question_id, description) VALUES(147, '-415');
INSERT INTO choice(question_id, description) VALUES(148, '91');
INSERT INTO choice(question_id, description) VALUES(148, '-691');
INSERT INTO choice(question_id, description) VALUES(148, '-24');
INSERT INTO choice(question_id, description) VALUES(148, '-848');
INSERT INTO choice(question_id, description) VALUES(148, '122');
INSERT INTO choice(question_id, description) VALUES(149, '-580');
INSERT INTO choice(question_id, description) VALUES(149, '762');
INSERT INTO choice(question_id, description) VALUES(149, '156');
INSERT INTO choice(question_id, description) VALUES(149, '-625');
INSERT INTO choice(question_id, description) VALUES(149, '1019');
INSERT INTO choice(question_id, description) VALUES(150, '-124');
INSERT INTO choice(question_id, description) VALUES(150, '-97');
INSERT INTO choice(question_id, description) VALUES(150, '586');
INSERT INTO choice(question_id, description) VALUES(150, '-300');
INSERT INTO choice(question_id, description) VALUES(150, '-79');
INSERT INTO choice(question_id, description) VALUES(151, '515');
INSERT INTO choice(question_id, description) VALUES(151, '490');
INSERT INTO choice(question_id, description) VALUES(151, '-747');
INSERT INTO choice(question_id, description) VALUES(151, '69');
INSERT INTO choice(question_id, description) VALUES(151, '-440');
INSERT INTO choice(question_id, description) VALUES(152, '785');
INSERT INTO choice(question_id, description) VALUES(152, '99');
INSERT INTO choice(question_id, description) VALUES(152, '-278');
INSERT INTO choice(question_id, description) VALUES(152, '-734');
INSERT INTO choice(question_id, description) VALUES(152, '-445');
INSERT INTO choice(question_id, description) VALUES(153, '-434');
INSERT INTO choice(question_id, description) VALUES(153, '275');
INSERT INTO choice(question_id, description) VALUES(153, '654');
INSERT INTO choice(question_id, description) VALUES(153, '411');
INSERT INTO choice(question_id, description) VALUES(153, '1399');
INSERT INTO choice(question_id, description) VALUES(154, '154');
INSERT INTO choice(question_id, description) VALUES(154, '-929');
INSERT INTO choice(question_id, description) VALUES(154, '12');
INSERT INTO choice(question_id, description) VALUES(154, '99');
INSERT INTO choice(question_id, description) VALUES(154, '27');
INSERT INTO choice(question_id, description) VALUES(155, '-224');
INSERT INTO choice(question_id, description) VALUES(155, '737');
INSERT INTO choice(question_id, description) VALUES(155, '806');
INSERT INTO choice(question_id, description) VALUES(155, '670');
INSERT INTO choice(question_id, description) VALUES(155, '-146');
INSERT INTO choice(question_id, description) VALUES(156, '-629');
INSERT INTO choice(question_id, description) VALUES(156, '-170');
INSERT INTO choice(question_id, description) VALUES(156, '748');
INSERT INTO choice(question_id, description) VALUES(156, '-400');
INSERT INTO choice(question_id, description) VALUES(156, '-66');
INSERT INTO choice(question_id, description) VALUES(157, '606');
INSERT INTO choice(question_id, description) VALUES(157, '390');
INSERT INTO choice(question_id, description) VALUES(157, '182');
INSERT INTO choice(question_id, description) VALUES(157, '-166');
INSERT INTO choice(question_id, description) VALUES(157, '-1066');
INSERT INTO choice(question_id, description) VALUES(158, '-456');
INSERT INTO choice(question_id, description) VALUES(158, '-391');
INSERT INTO choice(question_id, description) VALUES(158, '-444');
INSERT INTO choice(question_id, description) VALUES(158, '-14');
INSERT INTO choice(question_id, description) VALUES(158, '-475');
INSERT INTO choice(question_id, description) VALUES(159, '-471');
INSERT INTO choice(question_id, description) VALUES(159, '113');
INSERT INTO choice(question_id, description) VALUES(159, '987');
INSERT INTO choice(question_id, description) VALUES(159, '15');
INSERT INTO choice(question_id, description) VALUES(159, '1233');
INSERT INTO choice(question_id, description) VALUES(160, '951');
INSERT INTO choice(question_id, description) VALUES(160, '-252');
INSERT INTO choice(question_id, description) VALUES(160, '-799');
INSERT INTO choice(question_id, description) VALUES(160, '-194');
INSERT INTO choice(question_id, description) VALUES(160, '-1005');
INSERT INTO choice(question_id, description) VALUES(161, '-606');
INSERT INTO choice(question_id, description) VALUES(161, '811');
INSERT INTO choice(question_id, description) VALUES(161, '928');
INSERT INTO choice(question_id, description) VALUES(161, '-920');
INSERT INTO choice(question_id, description) VALUES(161, '-1050');
INSERT INTO choice(question_id, description) VALUES(162, '294');
INSERT INTO choice(question_id, description) VALUES(162, '-99');
INSERT INTO choice(question_id, description) VALUES(162, '284');
INSERT INTO choice(question_id, description) VALUES(162, '-376');
INSERT INTO choice(question_id, description) VALUES(162, '-1356');
INSERT INTO choice(question_id, description) VALUES(163, '-93');
INSERT INTO choice(question_id, description) VALUES(163, '789');
INSERT INTO choice(question_id, description) VALUES(163, '715');
INSERT INTO choice(question_id, description) VALUES(163, '-733');
INSERT INTO choice(question_id, description) VALUES(163, '-1534');
INSERT INTO choice(question_id, description) VALUES(164, '-192');
INSERT INTO choice(question_id, description) VALUES(164, '561');
INSERT INTO choice(question_id, description) VALUES(164, '159');
INSERT INTO choice(question_id, description) VALUES(164, '-799');
INSERT INTO choice(question_id, description) VALUES(164, '606');
INSERT INTO choice(question_id, description) VALUES(165, '-153');
INSERT INTO choice(question_id, description) VALUES(165, '157');
INSERT INTO choice(question_id, description) VALUES(165, '457');
INSERT INTO choice(question_id, description) VALUES(165, '595');
INSERT INTO choice(question_id, description) VALUES(165, '-1688');
INSERT INTO choice(question_id, description) VALUES(166, '-488');
INSERT INTO choice(question_id, description) VALUES(166, '-62');
INSERT INTO choice(question_id, description) VALUES(166, '-862');
INSERT INTO choice(question_id, description) VALUES(166, '-484');
INSERT INTO choice(question_id, description) VALUES(166, '-1212');
INSERT INTO choice(question_id, description) VALUES(167, '-807');
INSERT INTO choice(question_id, description) VALUES(167, '-54');
INSERT INTO choice(question_id, description) VALUES(167, '-614');
INSERT INTO choice(question_id, description) VALUES(167, '-530');
INSERT INTO choice(question_id, description) VALUES(167, '1180');
INSERT INTO choice(question_id, description) VALUES(168, '-123');
INSERT INTO choice(question_id, description) VALUES(168, '-676');
INSERT INTO choice(question_id, description) VALUES(168, '302');
INSERT INTO choice(question_id, description) VALUES(168, '488');
INSERT INTO choice(question_id, description) VALUES(168, '-66');
INSERT INTO choice(question_id, description) VALUES(169, '178');
INSERT INTO choice(question_id, description) VALUES(169, '-424');
INSERT INTO choice(question_id, description) VALUES(169, '-93');
INSERT INTO choice(question_id, description) VALUES(169, '-494');
INSERT INTO choice(question_id, description) VALUES(169, '1033');
INSERT INTO choice(question_id, description) VALUES(170, '-791');
INSERT INTO choice(question_id, description) VALUES(170, '-485');
INSERT INTO choice(question_id, description) VALUES(170, '-659');
INSERT INTO choice(question_id, description) VALUES(170, '257');
INSERT INTO choice(question_id, description) VALUES(170, '-1122');
INSERT INTO choice(question_id, description) VALUES(171, '695');
INSERT INTO choice(question_id, description) VALUES(171, '163');
INSERT INTO choice(question_id, description) VALUES(171, '279');
INSERT INTO choice(question_id, description) VALUES(171, '118');
INSERT INTO choice(question_id, description) VALUES(171, '-1495');
INSERT INTO choice(question_id, description) VALUES(172, '-340');
INSERT INTO choice(question_id, description) VALUES(172, '-760');
INSERT INTO choice(question_id, description) VALUES(172, '8');
INSERT INTO choice(question_id, description) VALUES(172, '313');
INSERT INTO choice(question_id, description) VALUES(172, '-150');
INSERT INTO choice(question_id, description) VALUES(173, '-621');
INSERT INTO choice(question_id, description) VALUES(173, '617');
INSERT INTO choice(question_id, description) VALUES(173, '-300');
INSERT INTO choice(question_id, description) VALUES(173, '-15');
INSERT INTO choice(question_id, description) VALUES(173, '658');
INSERT INTO choice(question_id, description) VALUES(174, '134');
INSERT INTO choice(question_id, description) VALUES(174, '840');
INSERT INTO choice(question_id, description) VALUES(174, '101');
INSERT INTO choice(question_id, description) VALUES(174, '-833');
INSERT INTO choice(question_id, description) VALUES(174, '1285');
INSERT INTO choice(question_id, description) VALUES(175, '614');
INSERT INTO choice(question_id, description) VALUES(175, '36');
INSERT INTO choice(question_id, description) VALUES(175, '444');
INSERT INTO choice(question_id, description) VALUES(175, '-919');
INSERT INTO choice(question_id, description) VALUES(175, '-1041');
INSERT INTO choice(question_id, description) VALUES(176, '-207');
INSERT INTO choice(question_id, description) VALUES(176, '-113');
INSERT INTO choice(question_id, description) VALUES(176, '747');
INSERT INTO choice(question_id, description) VALUES(176, '-542');
INSERT INTO choice(question_id, description) VALUES(176, '-157');
INSERT INTO choice(question_id, description) VALUES(177, '339');
INSERT INTO choice(question_id, description) VALUES(177, '-928');
INSERT INTO choice(question_id, description) VALUES(177, '888');
INSERT INTO choice(question_id, description) VALUES(177, '-522');
INSERT INTO choice(question_id, description) VALUES(177, '-755');
INSERT INTO choice(question_id, description) VALUES(178, '-383');
INSERT INTO choice(question_id, description) VALUES(178, '629');
INSERT INTO choice(question_id, description) VALUES(178, '-537');
INSERT INTO choice(question_id, description) VALUES(178, '795');
INSERT INTO choice(question_id, description) VALUES(178, '-445');
INSERT INTO choice(question_id, description) VALUES(179, '675');
INSERT INTO choice(question_id, description) VALUES(179, '-95');
INSERT INTO choice(question_id, description) VALUES(179, '-301');
INSERT INTO choice(question_id, description) VALUES(179, '-667');
INSERT INTO choice(question_id, description) VALUES(179, '1101');
INSERT INTO choice(question_id, description) VALUES(180, '620');
INSERT INTO choice(question_id, description) VALUES(180, '307');
INSERT INTO choice(question_id, description) VALUES(180, '874');
INSERT INTO choice(question_id, description) VALUES(180, '-193');
INSERT INTO choice(question_id, description) VALUES(180, '306');
INSERT INTO choice(question_id, description) VALUES(181, '704');
INSERT INTO choice(question_id, description) VALUES(181, '129');
INSERT INTO choice(question_id, description) VALUES(181, '-776');
INSERT INTO choice(question_id, description) VALUES(181, '210');
INSERT INTO choice(question_id, description) VALUES(181, '784');
INSERT INTO choice(question_id, description) VALUES(182, '-164');
INSERT INTO choice(question_id, description) VALUES(182, '-734');
INSERT INTO choice(question_id, description) VALUES(182, '-883');
INSERT INTO choice(question_id, description) VALUES(182, '-557');
INSERT INTO choice(question_id, description) VALUES(182, '-21');
INSERT INTO choice(question_id, description) VALUES(183, '245');
INSERT INTO choice(question_id, description) VALUES(183, '-592');
INSERT INTO choice(question_id, description) VALUES(183, '-215');
INSERT INTO choice(question_id, description) VALUES(183, '-971');
INSERT INTO choice(question_id, description) VALUES(183, '373');
INSERT INTO choice(question_id, description) VALUES(184, '388');
INSERT INTO choice(question_id, description) VALUES(184, '-415');
INSERT INTO choice(question_id, description) VALUES(184, '-875');
INSERT INTO choice(question_id, description) VALUES(184, '-737');
INSERT INTO choice(question_id, description) VALUES(184, '-687');
INSERT INTO choice(question_id, description) VALUES(185, '201');
INSERT INTO choice(question_id, description) VALUES(185, '-584');
INSERT INTO choice(question_id, description) VALUES(185, '-166');
INSERT INTO choice(question_id, description) VALUES(185, '509');
INSERT INTO choice(question_id, description) VALUES(185, '-262');
INSERT INTO choice(question_id, description) VALUES(186, '-998');
INSERT INTO choice(question_id, description) VALUES(186, '35');
INSERT INTO choice(question_id, description) VALUES(186, '-883');
INSERT INTO choice(question_id, description) VALUES(186, '-950');
INSERT INTO choice(question_id, description) VALUES(186, '1873');
INSERT INTO choice(question_id, description) VALUES(187, '-652');
INSERT INTO choice(question_id, description) VALUES(187, '-295');
INSERT INTO choice(question_id, description) VALUES(187, '-318');
INSERT INTO choice(question_id, description) VALUES(187, '246');
INSERT INTO choice(question_id, description) VALUES(187, '308');
INSERT INTO choice(question_id, description) VALUES(188, '-451');
INSERT INTO choice(question_id, description) VALUES(188, '-107');
INSERT INTO choice(question_id, description) VALUES(188, '-699');
INSERT INTO choice(question_id, description) VALUES(188, '983');
INSERT INTO choice(question_id, description) VALUES(188, '277');
INSERT INTO choice(question_id, description) VALUES(189, '-693');
INSERT INTO choice(question_id, description) VALUES(189, '961');
INSERT INTO choice(question_id, description) VALUES(189, '-297');
INSERT INTO choice(question_id, description) VALUES(189, '-211');
INSERT INTO choice(question_id, description) VALUES(189, '-1677');
INSERT INTO choice(question_id, description) VALUES(190, '495');
INSERT INTO choice(question_id, description) VALUES(190, '328');
INSERT INTO choice(question_id, description) VALUES(190, '-520');
INSERT INTO choice(question_id, description) VALUES(190, '-804');
INSERT INTO choice(question_id, description) VALUES(190, '-1561');
INSERT INTO choice(question_id, description) VALUES(191, '-371');
INSERT INTO choice(question_id, description) VALUES(191, '961');
INSERT INTO choice(question_id, description) VALUES(191, '-817');
INSERT INTO choice(question_id, description) VALUES(191, '339');
INSERT INTO choice(question_id, description) VALUES(191, '218');
INSERT INTO choice(question_id, description) VALUES(192, '772');
INSERT INTO choice(question_id, description) VALUES(192, '-480');
INSERT INTO choice(question_id, description) VALUES(192, '-480');
INSERT INTO choice(question_id, description) VALUES(192, '574');
INSERT INTO choice(question_id, description) VALUES(192, '617');
INSERT INTO choice(question_id, description) VALUES(193, '257');
INSERT INTO choice(question_id, description) VALUES(193, '219');
INSERT INTO choice(question_id, description) VALUES(193, '25');
INSERT INTO choice(question_id, description) VALUES(193, '750');
INSERT INTO choice(question_id, description) VALUES(193, '694');
INSERT INTO choice(question_id, description) VALUES(194, '-314');
INSERT INTO choice(question_id, description) VALUES(194, '73');
INSERT INTO choice(question_id, description) VALUES(194, '-761');
INSERT INTO choice(question_id, description) VALUES(194, '105');
INSERT INTO choice(question_id, description) VALUES(194, '-1439');
INSERT INTO choice(question_id, description) VALUES(195, '-315');
INSERT INTO choice(question_id, description) VALUES(195, '-393');
INSERT INTO choice(question_id, description) VALUES(195, '142');
INSERT INTO choice(question_id, description) VALUES(195, '953');
INSERT INTO choice(question_id, description) VALUES(195, '1064');
INSERT INTO choice(question_id, description) VALUES(196, '129');
INSERT INTO choice(question_id, description) VALUES(196, '-107');
INSERT INTO choice(question_id, description) VALUES(196, '55');
INSERT INTO choice(question_id, description) VALUES(196, '359');
INSERT INTO choice(question_id, description) VALUES(196, '645');
INSERT INTO choice(question_id, description) VALUES(197, '-116');
INSERT INTO choice(question_id, description) VALUES(197, '416');
INSERT INTO choice(question_id, description) VALUES(197, '-553');
INSERT INTO choice(question_id, description) VALUES(197, '-421');
INSERT INTO choice(question_id, description) VALUES(197, '972');
INSERT INTO choice(question_id, description) VALUES(198, '810');
INSERT INTO choice(question_id, description) VALUES(198, '114');
INSERT INTO choice(question_id, description) VALUES(198, '-509');
INSERT INTO choice(question_id, description) VALUES(198, '909');
INSERT INTO choice(question_id, description) VALUES(198, '330');
INSERT INTO choice(question_id, description) VALUES(199, '-645');
INSERT INTO choice(question_id, description) VALUES(199, '-78');
INSERT INTO choice(question_id, description) VALUES(199, '-248');
INSERT INTO choice(question_id, description) VALUES(199, '156');
INSERT INTO choice(question_id, description) VALUES(199, '1281');
INSERT INTO choice(question_id, description) VALUES(200, '-208');
INSERT INTO choice(question_id, description) VALUES(200, '486');
INSERT INTO choice(question_id, description) VALUES(200, '-38');
INSERT INTO choice(question_id, description) VALUES(200, '260');
INSERT INTO choice(question_id, description) VALUES(200, '-470');
